"""add summary column

Revision ID: 427db3e3d49e
Revises: 2e88fa0c5f46
Create Date: 2025-03-18 11:47:05.127429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "427db3e3d49e"
down_revision: Union[str, None] = "2e88fa0c5f46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
